# Generated by Django 2.2.6 on 2019-10-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project2s',
            options={'verbose_name': '接口', 'verbose_name_plural': '接口'},
        ),
        migrations.AlterModelTable(
            name='project2s',
            table='ta_interfaces',
        ),
    ]
