# Generated by Django 2.2.6 on 2019-10-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='ta_person',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='ta_projects',
        ),
    ]
